post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlpbmVzIiwiaWQiOiI1ZGYxNDNiOWQzZWU4ZDI1MzFmYmEwMWEiLCJpYXQiOjE1NzYxNjE1NzB9.AIpkBNaSz8TPIWTY7r43geazMjZFAWWtQQMB6JF1fvg

{
"title": "The Silmarillion",
"author" : "JRR Tolkien",
"url": "www.hs.fi",
"likes": 1600
}
