post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlpbmVzIiwiaWQiOiI1ZGYxNDNiOWQzZWU4ZDI1MzFmYmEwMWEiLCJpYXQiOjE1NzYxNTc3NDR9.-LHL9q_4xIwkZdnaDgc2eZWZzFCaCuiFoeT8qychBu4

{
"title": "The Hobbit",
"author" : "JRR Tolkien",
"url": "www.hs.fi",
"likes": 600
}
